### ISSUE TITLE
Vi sliter med sensor under robot

### ISSUE THREAD

**Issue by Simenullern** [Simenullern/basic_robot#2]
hva gjør vi?

**Comment by kjetkv** [comment]
Vi må søke assistanse hos studass

**Comment by vebjornpf** [comment]
hmm, dette er et problem ja

**Comment by Simenullern** [comment]
Update: Har testet to gamle roboter fra folk som er ferdig. Begge gruppene hadde root password uten tilgang. Har indikasjoner på at det er sumoen, og ikke sensor

**Comment by kjetkv** [comment]
Update2: Fått ny robot.. alt fungerer knirkefritt
